In [32]:
#!/usr/bin/env python
# -*- coding: latin-1 -*-
import pandas as pd # pandas is a data manipulation library
import numpy as np #provides numerical arrays and functions to manipulate the arrays efficiently
import logging
import difflib
import Levenshtein as lev
from tqdm.notebook import tqdm
import multiprocessing
import gensim
from gensim.models.doc2vec import Doc2Vec, TaggedDocument
import seaborn as sns
import matplotlib.pyplot as plt
import scipy
from scipy import spatial
import re
import movies_df_helper_functions as helper_fn
import evaluation_helper_functions as eval_fn
import random
import imp
import itertools
from sklearn.manifold import TSNE
from sklearn.cluster import AffinityPropagation
from nltk.translate.bleu_score import sentence_bleu
from nltk.translate.bleu_score import SmoothingFunction
import html
import csv
import re
#from sklearn.manifold import TSNE

from tabulate import tabulate
import decimal
from collections import Counter

imp.reload(eval_fn)
imp.reload(helper_fn)
%matplotlib inline

In [18]:
#load train data
#train_data_df = pd.read_csv('models/baseline_exp/train_data.csv')
train_data_df = pd.read_csv('imdb_doc2vec_train_data.csv')
#load genres test data
#genres_sample_df = pd.read_csv('test_data/genres_sample_movies_id_list.csv')
#load all genres lists df
#genres_df = pd.read_csv('test_data/movies_by_genre.csv')
#load all sequel and mixed data for plotting
#sequel_sampled_data_df = pd.read_csv('test_data/sequel_and_sampled_titles_df.csv')

In [19]:
#load model
model = Doc2Vec.load('model')

In [20]:
def assign_genre(genre_df, movie_id):
    romantic_comedy= genre_df.romantic_comedy.values.tolist()
    drama = genre_df.drama.values.tolist()
    adventure = genre_df.adventure.values.tolist()
    crime = genre_df.crime.values.tolist()
    action = genre_df.action.values.tolist()
    
    if movie_id in romantic_comedy:
        return 'Romantic_Comedy'
    else:
        if movie_id in drama:
            return 'Drama'
        else: 
            if movie_id in adventure:
                return 'Adventure'
            else: 
                if movie_id in crime:
                    return 'Crime'
                else: 
                    if movie_id in action: return 'Action'
                    else: 
                        return 'Unkown'

In [22]:
train_data_df

,Unnamed: 0,movie_id,title,genre,actor_name,director_name,writer_name,movie_sentence
0,0,robbery_under_arms_tt0000615,robbery under arms,['drama'],"['george_merriman', 'lance_vane', 'jim_gerald'...",['charles_macmahon'],['rolf_boldrewood'],"['george_merriman', 'lance_vane', 'jim_gerald'..."
1,1,hamlet_tt0000630,hamlet,['drama'],['fernanda_negri_pouget'],['mario_caserini'],['william_shakespeare'],"['fernanda_negri_pouget', 'drama', 'mario_case..."
2,2,don_álvaro_o_la_fuerza_del_sino_tt0000676,don álvaro o la fuerza del sino,['drama'],"['joaquín_carrasco', 'jaime_borrás']",['narciso_cuyàs'],['duque_de_rivas'],"['joaquín_carrasco', 'jaime_borrás', 'drama', ..."
3,3,"hamlet,_prince_of_denmark_tt0000886","hamlet, prince of denmark",['drama'],['jean_mounet-sully'],['gérard_bourgeois'],['william_shakespeare'],"['jean_mounet-sully', 'drama', 'gérard_bourgeo..."
4,4,locura_de_amor_tt0000941,locura de amor,['drama'],"['josé_durany', 'elvira_fremont', 'joaquín_car...","['ricardo_de_baños', 'alberto_marro']",['manuel_tamayo_y_baus'],"['josé_durany', 'elvira_fremont', 'joaquín_car..."
...,...,...,...,...,...,...,...,...
187645,187645,the_rehearsal_tt9916170,the rehearsal,['drama'],"['julia_ianina', 'pablo_lafuente', 'kelner_mac...",['tamar_guimaraes'],"['lillah_halla', 'melissa_de_raaf']","['julia_ianina', 'pablo_lafuente', 'kelner_mac..."
187646,187646,il_talento_del_calabrone_tt9916270,il talento del calabrone,['thriller'],"['marina_occhionero', 'sergio_castellitto', 'a...",['giacomo_cimini'],['lorenzo_collalti'],"['marina_occhionero', 'sergio_castellitto', 'a..."
187647,187647,coven_tt9916362,coven,"['drama', 'history', 'horror']","['alex_brendemühl', 'daniel_fanego', 'amaia_ab...",['pablo_agüero'],['katell_guillou'],"['alex_brendemühl', 'daniel_fanego', 'amaia_ab..."
187648,187648,kuambil_lagi_hatiku_tt9916538,kuambil lagi hatiku,['drama'],"['ria_irawan', 'sahil_shah', 'lala_karmela', '...",['azhar_kinoi_lubis'],"['arief_ash_siddiq', 'salman_aristo', 'rino_sa...","['ria_irawan', 'sahil_shah', 'lala_karmela', '..."
187649,187649,dankyavar_danka_tt9916706,dankyavar danka,['comedy'],"['suvarna_kale', 'makarand_anaspure', 'prakash...",['kanchan_nayak'],['sudhir_nikam'],"['suvarna_kale', 'makarand_anaspure', 'prakash..."

In [24]:
#Clean train_data_df
#remove the square brackets saved when generating the test data.It i snot a bug. Data can't be saved without as they act as a column separator in the csv file
train_data_df['actor_name'] = train_data_df.actor_name.apply(lambda actor: actor.replace('[','').replace(']','').replace("'", "") )
train_data_df['director_name'] = train_data_df.director_name.apply(lambda director: director.replace('[','').replace(']','').replace("'", "") )
train_data_df['writer_name'] = train_data_df.writer_name.apply(lambda writer: writer.replace('[','').replace(']','').replace("'", "") )
#train_data_df['country'] = train_data_df.country.apply(lambda country: country.replace('[','').replace(']','').replace("'", "") )
train_data_df['genre'] = train_data_df.genre.apply(lambda genre: genre.replace('[','').replace(']','').replace("'", "") )

train_data_df['actor_name'] = train_data_df.actor_name.apply(lambda actor: actor.split(',') )
train_data_df['director_name'] = train_data_df.director_name.apply(lambda director: director.split(',') )
train_data_df['writer_name'] = train_data_df.writer_name.apply(lambda writer: writer.split(',') )
#train_data_df['country'] = train_data_df.country.apply(lambda country: country.split(',') )
train_data_df['genre'] = train_data_df.genre.apply(lambda genre: genre.split(',') )

In [25]:
train_data_df['actor_name'] = train_data_df.actor_name.apply(lambda actor: [a.strip() for a in actor])
train_data_df['director_name'] = train_data_df.director_name.apply(lambda director: [d.strip() for d in director])
train_data_df['writer_name'] = train_data_df.writer_name.apply(lambda writer: [w.strip() for w in writer] )
#train_data_df['country'] = train_data_df.country.apply(lambda country: [c.strip() for c in country] )
train_data_df['genre'] = train_data_df.genre.apply(lambda genre: [g.strip() for g in genre])


train_data_df[train_data_df['movie_id'] == 'agony_(film)'].values

array([], shape=(0, 8), dtype=object)

In [26]:
train_data_df

,Unnamed: 0,movie_id,title,genre,actor_name,director_name,writer_name,movie_sentence
0,0,robbery_under_arms_tt0000615,robbery under arms,[drama],"[george_merriman, lance_vane, jim_gerald, will...",[charles_macmahon],[rolf_boldrewood],"['george_merriman', 'lance_vane', 'jim_gerald'..."
1,1,hamlet_tt0000630,hamlet,[drama],[fernanda_negri_pouget],[mario_caserini],[william_shakespeare],"['fernanda_negri_pouget', 'drama', 'mario_case..."
2,2,don_álvaro_o_la_fuerza_del_sino_tt0000676,don álvaro o la fuerza del sino,[drama],"[joaquín_carrasco, jaime_borrás]",[narciso_cuyàs],[duque_de_rivas],"['joaquín_carrasco', 'jaime_borrás', 'drama', ..."
3,3,"hamlet,_prince_of_denmark_tt0000886","hamlet, prince of denmark",[drama],[jean_mounet-sully],[gérard_bourgeois],[william_shakespeare],"['jean_mounet-sully', 'drama', 'gérard_bourgeo..."
4,4,locura_de_amor_tt0000941,locura de amor,[drama],"[josé_durany, elvira_fremont, joaquín_carrasco...","[ricardo_de_baños, alberto_marro]",[manuel_tamayo_y_baus],"['josé_durany', 'elvira_fremont', 'joaquín_car..."
...,...,...,...,...,...,...,...,...
187645,187645,the_rehearsal_tt9916170,the rehearsal,[drama],"[julia_ianina, pablo_lafuente, kelner_macêdo, ...",[tamar_guimaraes],"[lillah_halla, melissa_de_raaf]","['julia_ianina', 'pablo_lafuente', 'kelner_mac..."
187646,187646,il_talento_del_calabrone_tt9916270,il talento del calabrone,[thriller],"[marina_occhionero, sergio_castellitto, anna_f...",[giacomo_cimini],[lorenzo_collalti],"['marina_occhionero', 'sergio_castellitto', 'a..."
187647,187647,coven_tt9916362,coven,"[drama, history, horror]","[alex_brendemühl, daniel_fanego, amaia_aberast...",[pablo_agüero],[katell_guillou],"['alex_brendemühl', 'daniel_fanego', 'amaia_ab..."
187648,187648,kuambil_lagi_hatiku_tt9916538,kuambil lagi hatiku,[drama],"[ria_irawan, sahil_shah, lala_karmela, cut_min...",[azhar_kinoi_lubis],"[arief_ash_siddiq, salman_aristo, rino_sarjono]","['ria_irawan', 'sahil_shah', 'lala_karmela', '..."
187649,187649,dankyavar_danka_tt9916706,dankyavar danka,[comedy],"[suvarna_kale, makarand_anaspure, prakash_dhot...",[kanchan_nayak],[sudhir_nikam],"['suvarna_kale', 'makarand_anaspure', 'prakash..."

In [28]:
#create dictionary with the movie_id and title
movies_dict= dict(zip(train_data_df.movie_id, train_data_df.title))

# Manual Validation

In [58]:
#Manual check
movie_id = 'godzilla:_the_planet_eater_tt8478602'
#movie_id = 'the_bunker_(2001_film)'
#movie_id= 'just_go_with_it_tt1564367'
#movie_id='agony_(film)'
#movie_id= 'harry_potter_and_the_half-blood_prince_tt0417741'
#movie_id = 'toy_story_4_tt1979376'
#movie_id = 'tsar_(film)'
#movie_id='high_school_musical_3:_senior_year'
#movie_id= 'hook_(film)'
#movie_id="destiny_(1997_film)"
#movie_id="blade:_trinity"
movie_id='x-men_tt0120903'


similar_movies = model.docvecs.most_similar(movie_id, topn=10)
sim_movies_list = [sim[0] for sim in similar_movies]

sim_df= pd.DataFrame(columns=['Title','Similarity Ratio'])

for sim in similar_movies:
    #title = helper_fn.find_movie_title_by_id(sim[0], train_data_df)
    data = {'Title':  [sim[0]],'Similarity Ratio': [sim[1]]}
    tmp_df = pd.DataFrame(data, columns=['Title','Similarity Ratio'])
    sim_df = pd.concat([sim_df, tmp_df])   

common_features_df = eval_fn.get_common_attrs_cnt_for_sim_list(train_data_df, sim_movies_list, movie_id,'IMDb') 

result_df = sim_df.merge(common_features_df, left_on= ['Title'], right_on=['Title'], how='inner')

result_df.Title= result_df.Title.map(lambda t: (helper_fn.find_movie_title_by_id(t, train_data_df).values[0]).capitalize())

query_movie_title = helper_fn.find_movie_title_by_id(movie_id, train_data_df).values[0].capitalize()
print("\n")
print("Similarity for the movie title \"{}\"".format(query_movie_title))
display(tabulate(result_df, headers=result_df.columns,tablefmt='html', showindex=False))

#sim = docs_vectors.most_similar(positive= 'harry_potter_and_the_chamber_of_secrets_(film)', topn= 5)
#eval_fn.print_sim_list(similar_movies)

Similarity for the movie title "X-men"

'<table>\n<thead>\n<tr><th>Title                              </th><th style="text-align: right;">  Similarity Ratio</th><th style="text-align: right;">  Common Features Count</th></tr>\n</thead>\n<tbody>\n<tr><td>X2: x-men united                   </td><td style="text-align: right;">          0.968973</td><td style="text-align: right;">                      8</td></tr>\n<tr><td>Guyver: dark hero                  </td><td style="text-align: right;">          0.959449</td><td style="text-align: right;">                      2</td></tr>\n<tr><td>Star trek beyond                   </td><td style="text-align: right;">          0.95687 </td><td style="text-align: right;">                      3</td></tr>\n<tr><td>X-men: apocalypse                  </td><td style="text-align: right;">          0.956168</td><td style="text-align: right;">                      4</td></tr>\n<tr><td>Transformers: dark of the moon     </td><td style="text-align: right;">          0.947694</td><td style="text-align: right;">                      3</td></tr>\n<tr><td>Superman returns                   </td><td style="text-align: right;">          0.944847</td><td style="text-align: right;">                      3</td></tr>\n<tr><td>Transformers: revenge of the fallen</td><td style="text-align: right;">          0.94415 </td><td style="text-align: right;">                      3</td></tr>\n<tr><td>Untitled star trek sequel          </td><td style="text-align: right;">          0.943939</td><td style="text-align: right;">                      3</td></tr>\n<tr><td>Transformers: the last knight      </td><td style="text-align: right;">          0.94282 </td><td style="text-align: right;">                      3</td></tr>\n<tr><td>Man of steel                       </td><td style="text-align: right;">          0.941768</td><td style="text-align: right;">                      3</td></tr>\n</tbody>\n</table>'

Similarity for the movie title "Harry potter and the half-blood prince"

'<table>\n<thead>\n<tr><th>Title                                       </th><th style="text-align: right;">  Similarity Ratio</th><th style="text-align: right;">  Common Features Count</th></tr>\n</thead>\n<tbody>\n<tr><td>Harry potter and the deathly hallows: part 2</td><td style="text-align: right;">          0.998305</td><td style="text-align: right;">                      8</td></tr>\n<tr><td>Harry potter and the deathly hallows: part 1</td><td style="text-align: right;">          0.997763</td><td style="text-align: right;">                      8</td></tr>\n<tr><td>Harry potter and the order of the phoenix   </td><td style="text-align: right;">          0.995601</td><td style="text-align: right;">                      8</td></tr>\n<tr><td>Harry potter and the chamber of secrets     </td><td style="text-align: right;">          0.991   </td><td style="text-align: right;">                      7</td></tr>\n<tr><td>Harry potter and the sorcerer&#x27;s stone       </td><td style="text-align: right;">          0.988227</td><td style="text-align: right;">                      6</td></tr>\n<tr><td>Fantastic beasts and where to find them 3   </td><td style="text-align: right;">          0.987403</td><td style="text-align: right;">                      5</td></tr>\n<tr><td>Fantastic beasts: the crimes of grindelwald </td><td style="text-align: right;">          0.984705</td><td style="text-align: right;">                      4</td></tr>\n<tr><td>Fantastic beasts and where to find them     </td><td style="text-align: right;">          0.983666</td><td style="text-align: right;">                      4</td></tr>\n<tr><td>The gathering storm: a marauders fan film   </td><td style="text-align: right;">          0.964592</td><td style="text-align: right;">                      1</td></tr>\n<tr><td>Harry potter and the prisoner of azkaban    </td><td style="text-align: right;">          0.950076</td><td style="text-align: right;">                      7</td></tr>\n</tbody>\n</table>'

Similarity for the movie title "Godzilla vs. biollante"

'<table>\n<thead>\n<tr><th>Title                 </th><th style="text-align: right;">  Similarity Ratio</th><th style="text-align: right;">  Common Features Count</th></tr>\n</thead>\n<tbody>\n<tr><td>Shinuniwa mada hayai  </td><td style="text-align: right;">          0.94575 </td><td style="text-align: right;">                      3</td></tr>\n<tr><td>Hissatsu!: sure death!</td><td style="text-align: right;">          0.945284</td><td style="text-align: right;">                      1</td></tr>\n<tr><td>Sure death! mondo dies</td><td style="text-align: right;">          0.933358</td><td style="text-align: right;">                      2</td></tr>\n<tr><td>Futô fukutsu          </td><td style="text-align: right;">          0.931871</td><td style="text-align: right;">                      1</td></tr>\n<tr><td>Black rain            </td><td style="text-align: right;">          0.928179</td><td style="text-align: right;">                      1</td></tr>\n<tr><td>The war in space      </td><td style="text-align: right;">          0.920892</td><td style="text-align: right;">                      2</td></tr>\n<tr><td>Hissatsu shikakenin   </td><td style="text-align: right;">          0.920784</td><td style="text-align: right;">                      2</td></tr>\n<tr><td>Kuroi neko            </td><td style="text-align: right;">          0.920297</td><td style="text-align: right;">                      1</td></tr>\n<tr><td>Himeyuri no tô        </td><td style="text-align: right;">          0.917025</td><td style="text-align: right;">                      1</td></tr>\n<tr><td>Black statement book  </td><td style="text-align: right;">          0.912765</td><td style="text-align: right;">                      0</td></tr>\n</tbody>\n</table>'

In [38]:
imp.reload(eval_fn)

In [ ]:
eval_fn.find_common_attrs(train_data_df, movie_id, 'blade_(film)')

In [ ]:
#Find the count of every feature
sim_movies_deails_df = train_data_df.loc[train_data_df.apply(lambda movie: True if movie.movie_id in sim_movies_list else False, axis=1)]

sim_movies_deails_df.apply(lambda movie: len(movie.actor_name), axis=1)

movie_record = train_data_df[train_data_df.movie_id == movie_id]

def find_feature_cnt_for_movie(movie_record, col):
    col_list = movie_record[col].to_list()
    if col_list is not None:
        return len(col_list[0])
    else:
        return 0

actors = find_feature_cnt_for_movie(movie_record, 'actor_name')

actors

In [ ]:
for s in similar_movies:
    print(s[1])

# Visualization

In [54]:
#prepare data from the same movies used in the manual check
test_movies_list= ['godzilla_vs._biollante'
        ,'the_bunker_(2001_film)'
        ,'just_go_with_it'
        ,'agony_(film)'
        ,'harry_potter_and_the_half-blood_prince_(film)'
        ,'toy_story_4'
        ,'tsar_(film)'
        ,'high_school_musical_3:_senior_year'
        , 'hook_(film)'
        ,"destiny_(1997_film)"
        ]

In [ ]:
#Actors

In [55]:
#query each movie for most similar list
#save each query movie and the result in a dictionary
#for each group, retrieve actors for all the movies in the list

group_by_q_movie=[]
all_groups_actors=[]
for movie_id in test_movies_list:
    sims= model.docvecs.most_similar(movie_id,topn=5)
    g_movies=[]
    for s in sims:
        g_movies.append(s[0])
    group = {'g_id':movie_id, 'g_movies':g_movies}
    group_by_q_movie.append(group)
    
    
for group in group_by_q_movie:
    query_movie_id = group['g_id']
    sim_movies_id_list = group['g_movies']
    group_actors=[]
    group_movies=[]
    actors = helper_fn.find_actors_by_movie_id(query_movie_id, train_data_df)
    
    group_actors = group_actors + actors[0]
    #print(group_actors)
    group_movies.append(query_movie_id)    
   # print("group ID {}".format(query_movie_id))
    
    for movie_id in sim_movies_id_list:
        #print("sim movie id {} :".format(movie_id))
        actors = helper_fn.find_actors_by_movie_id(movie_id, train_data_df)
        group_actors = group_actors + actors[0]
        group_movies.append(movie_id)
        #print(group_actors)
    all_groups_actors.append({'g_id':query_movie_id, 'g_movies':group_movies, 'g_actors':group_actors})


group_actors_df = pd.DataFrame(data= {'movie_id':[g['g_id'] for g in all_groups_actors], 
                'movies_list':[g['g_movies'] for g in all_groups_actors],
               'actors_list':[g['g_actors'] for g in all_groups_actors]
               })


#display(group_actors_df)

data_target_list=[]
movies_target_list=[]
actors_target_list=[]

for group in all_groups_actors:
    movies_target_list = movies_target_list + list(itertools.product([group['g_id']], group['g_movies']))
print(len(movies_target_list))
x_movies_df= pd.DataFrame(data= list(set(movies_target_list)), columns=['Y','X'])
x_movies_df['type']= 'movie'

    
for group in all_groups_actors:
    actors_target_list = actors_target_list + list(itertools.product([group['g_id']], group['g_actors']))
print(len(actors_target_list))
x_actors_df= pd.DataFrame(data= list(set(actors_target_list)), columns=['Y','X'])
x_actors_df['type']= 'actor'

final_df = x_actors_df.append(x_movies_df)

TypeError: '<' not supported between instances of 'str' and 'int'

In [ ]:
###Visualization
print(len(final_df))

final_df.reset_index(drop=True, inplace= True)
y=[]
data_X = []
type_x =[]
final_df['title']= final_df.apply(lambda row: helper_fn.find_movie_title_by_id(row.Y,train_data_df).values[0], axis=1)
final_df['title'] = final_df['title'].str.capitalize()
#y_vec = [model[tag] for tag in y]

doctags= model.docvecs.doctags
vocab = model.wv.vocab
final_df = final_df.sample(frac=1)
plt.rcParams["figure.figsize"] = [8,6]
data_X_vec=[]
for tag in final_df['X'].values :                
    if tag in doctags:
        tag_vec= model[tag] 
    else:
        if tag in vocab:
            tag_vec= model.wv[tag] 
        else:
            tag_vec=[0]*50
    data_X_vec.append(tag_vec)
final_df['X_vec']=data_X_vec

tsne=  TSNE(perplexity= 50, n_components=2, init='pca', n_iter=7000, random_state=23)

tsne_obj= tsne.fit_transform(final_df.X_vec.to_list())

tsne_df = pd.DataFrame({'X':tsne_obj[:,0],
                        'Y':tsne_obj[:,1],
                        'movie':final_df.title.to_list(),
                         'X_type':final_df.type.to_list()})

#sns.set(rc={'figure.figsize':(11.7,8.27)})


#movies_only=tsne_df[tsne_df['X_type']=='actor']

In [ ]:
sns.set_context('paper')
palette=['purple','red','orange','brown','blue','dodgerblue','green','lightgreen','darkcyan', 'black']
g = sns.scatterplot(x="X", y="Y", data=tsne_df, palette= palette, hue="movie");

tsne_df.apply(lambda point: g.scatter(point['X'], point['Y'], marker=find_marker(point['X_type'])), axis=1)

              



g.legend(loc='center left', bbox_to_anchor=(1.00, 0.5), ncol=1)

In [ ]:
def find_marker(type_X):
    if type_X == 'movie':
        return "o"
    else:
        if type_X == 'actor':
            return "s"

In [ ]:
movie_id='agony_(film)'
sims= model.docvecs.most_similar(movie_id,topn=5)
eval_fn.calculate_BLEU_score(movie_id, sims,train_data_df)

In [ ]:
#visialize movies grouped by the query movie_id- for each movie in the test set, generate the sim list and save them in a dict with the query movie as the key
#for each group, plot the query movie and the sim list using distinct color
#generate similarity list for each movie in the test set
vis_group_by_q_movie=[]
for movie_id in test_movies_list:
    sims= model.docvecs.most_similar(movie_id)
    g_movies=[]
    for s in sims:
        g_movies.append(s[0])
    group = {'g_id':movie_id, 'g_movies':g_movies}
    vis_group_by_q_movie.append(group)
#print(vis_group_by_q_movie)    

data_target_list=[]
for group in vis_group_by_q_movie:
    data_target_list = data_target_list + list(itertools.product([group['g_id']], group['g_movies']))
y=[]
data_X = []

#print(data_target_list)

for pair in data_target_list:
    title = helper_fn.find_movie_title_by_id(pair[0],train_data_df)
    y.append(title.values[0].capitalize())
    data_X.append(pair[1])

data_X_vec = [model[tag] for tag in data_X]
tsne=  TSNE(perplexity= 5, n_components=2, init='pca', n_iter=5000, random_state=23)
tsne_obj= tsne.fit_transform(data_X_vec)
tsne_df = pd.DataFrame({'X':tsne_obj[:,0],
                        'Y':tsne_obj[:,1],
                        'movie':y})

sns.set_context("notebook")
g=sns.scatterplot(x="X", y="Y",
              hue="movie",
              palette=['purple','red','orange','brown','blue',
                       'dodgerblue','green','lightgreen','darkcyan', 'black'],
              legend='full',
              data=tsne_df);
plt.title('Model generated movies with similarity')
g.figure.savefig("generated_simialr_movies.png")

g.legend(loc='center left', bbox_to_anchor=(1.00, 0.5), ncol=1)

In [ ]:
def split_list(col):

In [ ]:
#further analysis to the results in visualizing the 10 movies and their simialr ones
#get list of genres for each group

all_group_genres_list = []
for group in vis_group_by_q_movie: 
    group_genres_list=[]
    id_genres_list = []
    #genres for the query movie
    movie_genres = helper_fn.find_movie_genre_by_id(group['g_id'], train_data_df)
    id_genres_list = id_genres_list + movie_genres.to_list()[0]
    
    for movie_id in group['g_movies']:
        movie_genres = helper_fn.find_movie_genre_by_id(movie_id, train_data_df)
        group_genres_list = group_genres_list + movie_genres.tolist()[0]
     #   print(group_genres_list[0])
    g_genres={'g_id':group['g_id'], 'q_genres':id_genres_list,'g_genres': list(set(group_genres_list))}
    all_group_genres_list.append(g_genres)

group_genres_df = pd.DataFrame(data= {'movie_id':[g['g_id'] for g in all_group_genres_list]
                                      ,'q_genres':[g['q_genres'] for g in all_group_genres_list]
                                      ,'genres_list':[g['g_genres'] for g in all_group_genres_list]})

group_genres_df['q_genres'] = group_genres_df.apply(lambda row: '|'.join(row['q_genres']), axis=1)
group_genres_df['genres_list'] = group_genres_df.apply(lambda row: '|'.join(row['genres_list']), axis=1)
display(tabulate(group_genres_df, headers=['Query Movie', "Query Movie Genres", "Similar movies genres"],tablefmt='html', showindex=False))
group_genres_df.to_excel("models/exp1/sim_gen_list.xlsx", index=False)
#group_genres_df

# Calculate the ranking score for a model

In [51]:
#prepare test data
test_titles = []
test_titles= ['shrek','star trek','blade','toy story 4','pitch perfect','harry potter','godzilla','paddington','x-men']
test_data= eval_fn.build_movie_sequel_test_data(train_data_df, test_titles)

rank_score_list = eval_fn.calculate_rank_score(model,test_data,5)
group_rank_df = pd.DataFrame(data= {'group_id':[g['group_id'] for g in rank_score_list], 'score':[g['group_score'] for g in rank_score_list]})
group_rank_df.append(group_rank_df.sum(numeric_only=True), ignore_index=True)
group_rank_df.sort_values(by=['score'], ascending= False, inplace=True)
group_rank_df.loc['Column_Total']= group_rank_df.sum(numeric_only=True, axis=0)
group_rank_df.iloc[len(group_rank_df)-1].group_id= "Total"
display(tabulate(group_rank_df, headers=['Group', "Rank Score"],tablefmt='html', colalign=("right", "left"),showindex=False))

'<table>\n<thead>\n<tr><th style="text-align: right;">                                                 Group</th><th>Rank Score  </th></tr>\n</thead>\n<tbody>\n<tr><td style="text-align: right;">                  godzilla:_the_planet_eater_tt8478602</td><td>129         </td></tr>\n<tr><td style="text-align: right;">harry_potter_and_the_deathly_hallows:_part_2_tt1201607</td><td>120         </td></tr>\n<tr><td style="text-align: right;">star_trek_enterprise_ii:_der_anfang_vom_ende_tt9899716</td><td>103         </td></tr>\n<tr><td style="text-align: right;">                                shrek_retold_tt9334162</td><td>69          </td></tr>\n<tr><td style="text-align: right;">                             pitch_perfect_3_tt4765284</td><td>27          </td></tr>\n<tr><td style="text-align: right;">                           x-men:_apocalypse_tt3385516</td><td>21          </td></tr>\n<tr><td style="text-align: right;">                          blade_breaking_ice_tt9698056</td><td>14          </td></tr>\n<tr><td style="text-align: right;">                                paddington_2_tt4468740</td><td>10          </td></tr>\n<tr><td style="text-align: right;">                                 toy_story_4_tt1979376</td><td>0           </td></tr>\n<tr><td style="text-align: right;">                                                   nan</td><td>493         </td></tr>\n</tbody>\n</table>'

In [ ]:
#Calculate model BLEU score
test_titles = []
test_titles= ['shrek','star trek','blade','toy story 4','pitch perfect','harry potter','godzilla','paddington','x-men']
test_data= eval_fn.build_movie_sequel_test_data(train_data_df, test_titles)
bleu_score = eval_fn.calculate_model_bleu_score(model, test_data, train_data_df, 5)
bleu_score

In [57]:
test_titles= ['shrek','star trek','blade','toy story 4','pitch perfect','harry potter','godzilla','paddington','x-men']
test_data= eval_fn.build_movie_sequel_test_data(train_data_df, test_titles)
test_data

[['shrek_tt0126029',
  'shrek_2_tt0298148',
  'shrek_the_third_tt0413267',
  'shrek_forever_after_tt0892791',
  'shrek_the_musical_tt3070936',
  'shrek_retold_tt9334162'],
 ['star_trek:_the_motion_picture_tt0079945',
  'star_trek_ii:_the_wrath_of_khan_tt0084726',
  'star_trek_vi:_the_undiscovered_country_tt0102975',
  'star_trek:_generations_tt0111280',
  'star_trek:_nemesis_tt0253754',
  'star_trek_tt0796366',
  'star_trek:_operation_beta_shield_tt1206087',
  'star_trek_into_darkness_tt1408101',
  'star_trek_beyond_tt2660888',
  'star_trek:_enterprise_-_in_conversation_-_the_first_crew_tt3120406',
  'star_trek:_horizon_tt3854562',
  'star_trek:_captain_pike_tt4669408',
  'star_trek:_the_paradise_makers_tt7264946',
  'star_trek_first_frontier_tt9753990',
  'star_trek:_the_infinite_chain_tt9870502',
  'star_trek:_the_final_darkness_tt9876412',
  'star_trek_enterprise_ii:_der_anfang_vom_ende_tt9899716'],
 ['blade_of_penitence_tt0018606',
  'blade_tt0069797',
  'blade_runner_tt0083658',
  'blades_tt0096936',
  'blade_of_fury_tt0108622',
  'blade_tt0120611',
  'blade_ii_tt0187738',
  'blade_of_fury_tt0202027',
  'blade_tt0250398',
  'blade:_trinity_tt0359013',
  'blades_of_glory_tt0445934',
  'blade_of_the_assassin_tt10545940',
  'blade_the_iron_cross_tt10887344',
  'blade_and_termeh_tt12832150',
  'blade_of_the_phantom_master_tt1467299',
  'blades_of_blood_tt1730695',
  'blade_runner_2049_tt1856101',
  'blade_of_the_immortal_tt5084170',
  'blade_black_hidden_avenger_tt6791344',
  'blade_breaking_ice_tt9698056'],
 ['toy_story_4_tt1979376'],
 ['pitch_perfect_tt1981677',
  'pitch_perfect_2_tt2848292',
  'pitch_perfect_3_tt4765284'],
 ["harry_potter_and_the_sorcerer's_stone_tt0241527",
  'harry_potter_and_the_chamber_of_secrets_tt0295297',
  'harry_potter_and_the_prisoner_of_azkaban_tt0304141',
  'harry_potter_and_the_goblet_of_fire_tt0330373',
  'harry_potter_and_the_order_of_the_phoenix_tt0373889',
  'harry_potter_and_the_half-blood_prince_tt0417741',
  'harry_potter_and_the_deathly_hallows:_part_1_tt0926084',
  'harry_potter_and_the_deathly_hallows:_part_2_tt1201607'],
 ['godzilla_tt0047034',
  'godzilla_raids_again_tt0048127',
  'godzilla_vs._hedorah_tt0067148',
  'godzilla_vs._gigan_tt0068371',
  'godzilla_vs._megalon_tt0070122',
  'godzilla_vs._mechagodzilla_tt0071565',
  'godzilla_vs._biollante_tt0097444',
  'godzilla_and_mothra:_the_battle_for_earth_tt0104352',
  'godzilla_vs._mechagodzilla_ii_tt0107027',
  'godzilla_vs._spacegodzilla_tt0109916',
  'godzilla_tt0120685',
  'godzilla_2000_tt0188640',
  'godzilla:_king_of_the_monsters!_tt0197521',
  'godzilla_vs._megaguirus_tt0255198',
  'godzilla,_mothra_and_king_ghidorah:_giant_monsters_all-out_attack_tt0279112',
  'godzilla_against_mechagodzilla_tt0314111',
  'godzilla:_tokyo_s.o.s._tt0366526',
  'godzilla_tt0831387',
  'godzilla_tt12182062',
  'godzilla:_king_of_the_monsters_tt3741700',
  'godzilla_vs._kong_tt5034838',
  'godzilla_vs._wolfman_tt5567368',
  'godzilla:_planet_of_the_monsters_tt5979874',
  'godzilla:_city_on_the_edge_of_battle_tt8015080',
  'godzilla:_the_planet_eater_tt8478602'],
 ['paddington_tt1109624', 'paddington_2_tt4468740'],
 ['x-men_tt0120903',
  'x-men:_the_last_stand_tt0376994',
  'x-men_origins:_wolverine_tt0458525',
  'x-men:_first_class_tt1270798',
  'x-men:_days_of_future_past_tt1877832',
  'x-men:_apocalypse_tt3385516']]

In [ ]:
len(vis_genres_sample_df)

## visualize movies by genre
#genres_sample_df contains movies from the genres 'Romantic_Comedy','Drama','Adventure','Crime','Action','Unknown'

In [ ]:
y=[]
data_X = []

#print(data_target_list)



vis_genres_sample_df = genres_sample_df.copy()

vis_genres_sample_df['data_X_vec']= vis_genres_sample_df.apply(lambda movie:model[movie.movie_id], axis=1)
vis_genres_sample_df['y']= vis_genres_sample_df.apply(lambda movie: assign_genre(genres_df, movie.movie_id), axis=1)

data_X_vec = list(vis_genres_sample_df['data_X_vec'].values)
y = vis_genres_sample_df['y']
tsne=  TSNE(perplexity= 5, n_components=2, init='pca', n_iter=5000, random_state=23)
tsne_obj= tsne.fit_transform(data_X_vec)
tsne_df = pd.DataFrame({'X':tsne_obj[:,0],
                        'Y':tsne_obj[:,1],
                        'movie':y})
tsne_df.head()
sns.scatterplot(x="X", y="Y",
              data=tsne_df);

g=sns.scatterplot(x="X", y="Y",
              hue="movie",
         #     palette=['purple','red','orange','brown','blue','black'],
              legend='full',
              data=tsne_df);
plt.title('Movies grouped by genre ')
g.legend(loc='center left', bbox_to_anchor=(1.00, 0.5), ncol=1)

## plot sequelmovies with some noise data with labels

In [ ]:
def tsne_plot_doc2vec(model, samples,movies_dict,height, width):
    "Creates and TSNE model and plots it"
    labels = []
    tokens = []
    

    for doc in samples:
        tokens.append(model[doc])
        labels.append(movies_dict[doc])
    
    tsne_model = TSNE(perplexity=40, n_components=2, init='pca', n_iter=2500, random_state=23)
    new_values = tsne_model.fit_transform(tokens)

    x = []
    y = []
    for value in new_values:
        x.append(value[0])
        y.append(value[1])
        
    plt.figure(figsize=(height, width)) 
    for i in range(len(x)):
        plt.scatter(x[i],y[i])
        plt.annotate(labels[i],
                     xy=(x[i], y[i]),
                     xytext=(5, 2),
                     textcoords='offset points',
                     ha='right',
                     va='bottom')
   # plt.ylim(1, -7)
   # plt.xlim(-7,-1)
    
    
    plt.title('Similar and non-similar movies')
    plt.show()
    #plt.figimage.savefig('movies_labels_large.png',  bbox_inches='tight')
    plt.close()

In [ ]:
tsne_plot_doc2vec(model, sequel_sampled_data_df.movie_id,movies_dict,10, 10)

## Not sure what is this for

In [ ]:
def tsne_plot_doc2vec_categorized(model, samples,movies_dict, w,h):
    "Creates and TSNE model and plots it"
    labels = []
    tokens = []
    colors = []
    

    for doc in samples:
        tokens.append(model[doc])
        labels.append(movies_dict[doc])
        colors.append(assign_color(genres_df, doc))
    
    tsne_model = TSNE(perplexity=50, n_components=2, init='pca', n_iter=2500, random_state=23)
    new_values = tsne_model.fit_transform(tokens)

    x = []
    y = []
    for value in new_values:
        x.append(value[0])
        y.append(value[1])
        
    plt.figure(figsize=(w, h)) 
    for i in range(len(x)):
        plt.scatter(x[i],y[i],color= colors[i][0] )
        plt.annotate('', #labels[i],
                     xy=(x[i], y[i], ),
                     xytext=(5, 2),
                     textcoords='offset points',
                     ha='right',
                     va='bottom')
   # plt.xlim(-4.0, -1.0)
  #  display(HTML("<b>%d words most similar to '%s'</b>" % (n,word)))
    plt.title('Movies Distribution by Genre')
    plt.legend( labels=['Romantic_Comedy','Drama','Adventure','Crime','Action','Unknown'])
    plt.savefig('movies_genre.png')
   # plt.show(block=False)
    plt.show()
genres_sample_df

In [ ]:
tsne_plot_doc2vec_categorized(model, set(genres_sample_df[0:100].movie_id), movies_dict, 12,12)

In [ ]:
genre_samples= genres_sample_df.movie_id.values.tolist()
len(genre_samples)

In [ ]:
col_data=train_data_df[col_name]
val_list=[]
for data in col_data:
    for val in data:
        val_list.append(val)
occurence_count = Counter(val_list)
high_cnt = occurence_count.most_common(10)[0:10]
x= [cnt[0] for cnt in high_cnt ]

In [ ]:
tsne_plot_doc2vec(model, set(genre_samples[0:100]), movies_dict)

In [ ]:
from seaborn import sns

In [ ]:
#Plot movies by features

def plot_movies_by_feature(col_name, train_data_df, sample_size):
    col_data=train_data_df[col_name]
    val_list=[]
    for data in col_data:
        for val in data:
            val_list.append(val)

    occurence_count = Counter(val_list)
    print(len(occurence_count))
    high_cnt = occurence_count.most_common(sample_size)[0:sample_size]
    val_list= [cnt[0] for cnt in high_cnt ]
    print(val_list)
    
    movies_val_dict={}

    #val_list = random.sample(val_list,sample_size)
    for val in val_list:
        movies_val_dict[val] = helper_fn.find_movies_by_col_value(col_name, val, train_data_df)    
    
    data_target_list=[]
    for key in val_list:
        for val in movies_val_dict[key]:
            data_target_list.append((key,val))
    y=[]
    data_X = []

    for pair in data_target_list:
        y.append(pair[0])
        data_X.append(pair[1])

    data_X_vec = [model[tag] for tag in data_X]
    sns.set_context('notebook')
    tsne=  TSNE(perplexity= 50, n_components=2, init='pca', n_iter=5000, random_state=23)
    tsne_obj= tsne.fit_transform(data_X_vec)
    tsne_df = pd.DataFrame({'X':tsne_obj[:,0],
                        'Y':tsne_obj[:,1],
                        col_name:y})
    return tsne_df

def draw_plot(tsne_df, col_name, title,filename):
   # sns.set_palette(sns.color_palette("default", 20))
    #sns.color_palette()
    tsne_df[col_name] = tsne_df[col_name].apply(lambda c: c[1:] if c.startswith('_') else c)
    g=sns.scatterplot(x="X", y="Y",
                  hue=col_name,
              #    hue_order= cat_order,
                #  palette=['purple','red','orange'],
                  legend= 'full',            
                  data=tsne_df);
    
    g.set_title(title)
    #g.set_xlim(-600, 800)
    #g.set_ylim(-800, 600)
    g.legend(loc='center left', bbox_to_anchor=(1.00, 0.5), ncol=1)
    g.figure.savefig(filename)
    plt.close

In [ ]:
sample_size= 5
#col_name= 'actor_name' #10 actors
#col_name='writer_name' #10 samples
#col_name='director_name' #10
#col_name='country' #10 samples
#col_name='genre' #top 10

plot_df = plot_movies_by_feature(col_name,train_data_df, sample_size)
title= "Movies grouped by "+col_name
filename= col_name+"_plot.png"

In [ ]:
draw_plot(plot_df,col_name, title,filename )

In [ ]:
len(plot_df)

In [ ]:
def show_closest_line(similar_movies, query_movie, n):
   # display(html.HTML("<b>%d words most similar to '%s'</b>" % (n, query_movie)))
    
    tops = similar_movies
    
    items = [item[0] for item in tops]
    sims = [item[1] for i,item in enumerate(tops)]
    
    fig = plt.figure(num=None, figsize=(10, 6), dpi=80, facecolor='w', edgecolor='k')
    ax = fig.add_subplot(111)

    
    plt.xticks(range(n), [i+1 for i in range(n)])
    plt.xlabel('Rank')
    plt.ylabel('Similarity')
    plt.xlim(-1,n)

    
    ax.plot(sims, color="purple", alpha=0.5)
    
    for item, x, y in zip(items, range(n), sims):
        ax.annotate( item, xy=(x, y), xytext=(20, -7), textcoords='offset points', 
                     ha='right', va='bottom', color='orange', fontsize=14 )

    
    
    
    plt.show()